### ISSUE TITLE
Support streams

### ISSUE THREAD

**Issue by stephenplusplus** [fhinkel/teeny-request#1]
I'm not clear exactly how this integrates with the @google-cloud/* modules, but if this is the library we're using instead of request, I believe we will need stream support as well. Sorry if this is already covered, and I just missed it.

**Comment by fhinkel** [comment]
Some client libraries like translate don't use streams. See [this](https://github.com/googleapis/nodejs-translate/pull/98#issuecomment-413870116) comment.
