### ISSUE TITLE
Set up CI

### ISSUE THREAD

**Issue by JustinBeckwith** [fhinkel/teeny-request#12]
It looks like there's no CI set up here quite yet :) It would be rad to get Travis or CircleCI setup!

**Comment by kinwa91** [comment]
ping @fhinkel - if you don't have the capacity, I can help with configuring CI - this will make publishing new versions easier :)

**Comment by JustinBeckwith** [comment]
I think we would need admin.

**Comment by fhinkel** [comment]
It's happening: https://github.com/fhinkel/teeny-request/pull/29
