### ISSUE TITLE
Module can't be casted to `typeof request` in 3.9.1

### ISSUE THREAD

**Issue by kjin** [fhinkel/teeny-request#25]
It seems like `teenyRequest` doesn't have the same interface as `request` in 3.9.1, according to TypeScript:

```
src/trace-writer.ts:83:26 - error TS2352: Conversion of type 'typeof teenyRequest' to type 'RequestAPI<Request, CoreOptions, RequiredUriUrl>' may be a mistake because neither type sufficiently overlaps with the other. If this was intentional, convert the expression to 'unknown' first.
  Property 'get' is missing in type 'typeof teenyRequest'.

83           requestModule: teenyRequest as typeof r,
```

I didn't observe this with 3.9.0.

I can help fix this, but given the recency of the changes it seems like @kinwa91 or @JustinBeckwith might have a better idea of where the fix is?

**Comment by fhinkel** [comment]
@kjin Thanks for reporting this. @JustinBeckwith Do you want to fix it or should I revert for now?

**Comment by JustinBeckwith** [comment]
I'll take a look.
