### ISSUE TITLE
Streaming mode is handling errors

### ISSUE THREAD

**Issue by stephenplusplus** [fhinkel/teeny-request#39]
Currently in stream mode, if you make a request to a 404 endpoint, it will emit the `error` event with the response body. In callback mode, `err` will be null.

I noticed this while investigating https://github.com/googleapis/nodejs-storage/issues/720. [`retry-request`](http://gitnpm.com/retry-request) uses the response from this library to decide whether a request should be retried: https://github.com/stephenplusplus/retry-request/blob/48a8ec0ce54805ab8ea41edc8c89363a09c886d9/index.js#L168.

The `request` library doesn't treat a 404 as an error, for example. It reserves the `err` argument for things like a DNS lookup failure. Anything else must be parsed by the caller and self-determined to be an error.

**Comment by stephenplusplus** [comment]
cc @JustinBeckwith @bcoe

**Comment by bcoe** [comment]
@stephenplusplus gotcha, so rather than a 404 bubbling to the client immediately, we retry with a backoff? definitely feels like the 404 should be in the errback.

**Comment by stephenplusplus** [comment]
I'm going to work on a PR that gets rid of the error handling in streams, to match the way it works in callback mode.

**Comment by fhinkel** [comment]
Thank you!
